#Name of workflow
name: 'test and lint project'

#Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:

    #The type of machine to run the job on
    runs-on:  ubuntu-latest

    strategy:
      #Node version list
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
      # Run install project
    - name: npm install
      run: |
        make install
      env:
        CI: true
    - name: run litner
      run: |
        make lint
